language: python
sudo: required
env:
  global:
    - DISPLAY=:99.0
python:
  - "2.7"
addons:
  firefox: "latest"
virtualenv:
  system_site_packages: true
services:
  - docker
before_install:
  - sh -e /etc/init.d/xvfb start
  - docker run -d -p 4444:4444 --name selenium-hub -e GRID_TIMEOUT=10000 selenium/hub
  - docker run -d --dns 8.8.8.8 --link selenium-hub:hub selenium/node-firefox
  - docker run -d --dns 8.8.8.8 --link selenium-hub:hub selenium/node-chrome
install:
  - pip nose
script:
  - python setup.py install
  - nosetests anybox/nose_selenium/tests/ -v -s --log-config logging.conf
  - nosetests examples/ -v -s --log-config logging.conf --with-selenium --processes 2 --process-timeout 5
